#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VeeKee.Resource", IsApplication=true)]

namespace VeeKee
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int connection_error_red = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int primary_dark_green = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int primary_green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int primary_text_grey = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int secondary_text_grey = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int refresh = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int settings = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int VeeKeeIcon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int connectiontoolbar = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int refresh_button = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int settings_button = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int vpnLinearLayout = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int vpnListView = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int vpnName = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int vpnSwitch = 2131296259;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int VpnRow = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int connectionrefreshmenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int settingsmenu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int CheckingVpnStatusMessage = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int CheckingVpnStatusTitle = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int DisablingVpnMessage = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int EnablingVpnMessage = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int NotConnectedToCorrectWifiMessage = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int NotConnectedToWifiMessage = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int RefreshItemTitle = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int RouterConnectionAuthorizationIssueMessage = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int RouterIpAddressPreferenceKey = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int RouterIpAddressPreferenceTitle = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int RouterPasswordPreferenceKey = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int RouterPasswordPreferenceTitle = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int RouterPortPreferenceKey = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int RouterPortPreferenceTitle = 2131099667;
			
			// aapt resource value: 0x7f06000b
			public const int RouterPreferenceCategoryTitle = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int RouterUsernamePreferenceKey = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int RouterUsernamePreferenceTitle = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int SettingsItemTitle = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int UpdatingVpnTitle = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int VpnItemPreferenceCategoryTitle = 2131099660;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int VeekeeTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
