#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VeeKee.Resource", IsApplication=true)]

namespace VeeKee
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int connection_error_red = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int primary_dark_green = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int primary_green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int primary_text_grey = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int secondary_text_grey = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int refresh = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int settings = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int VeeKeeIcon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int connectiontoolbar = 2131361792;
			
			// aapt resource value: 0x7f0a0005
			public const int refresh_button = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int settings_button = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int vpnLinearLayout = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int vpnListView = 2131361793;
			
			// aapt resource value: 0x7f0a0004
			public const int vpnName = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int vpnSwitch = 2131361795;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060002
			public const int ConnectionTimeoutSeconds = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int DefaultRouterSshPort = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int VpnItemCount = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int VpnRow = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int connectionrefreshmenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int settingsmenu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int CheckingVpnStatusMessage = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int CheckingVpnStatusTitle = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int ConnectingToRouterStatusMessage = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int ConnectionTimeoutMessage = 2131165192;
			
			// aapt resource value: 0x7f070019
			public const int DefaultRouterIpAddress = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int DefaultRouterUsername = 2131165210;
			
			// aapt resource value: 0x7f07000b
			public const int DisablingVpnFormat = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int EnablingVpnFormat = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int NetworkIssueMessage = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int NotConnectedToCorrectWifiMessage = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int NotConnectedToWifiMessage = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int RefreshItemTitle = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int RouterConnectionAuthorizationIssueMessage = 2131165190;
			
			// aapt resource value: 0x7f070012
			public const int RouterIpAddressPreferenceKey = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int RouterIpAddressPreferenceTitle = 2131165201;
			
			// aapt resource value: 0x7f070016
			public const int RouterPasswordPreferenceKey = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int RouterPasswordPreferenceTitle = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int RouterPreferenceCategoryTitle = 2131165199;
			
			// aapt resource value: 0x7f070018
			public const int RouterSshPortPreferenceKey = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int RouterSshPortPreferenceTitle = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int RouterUsernamePreferenceKey = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int RouterUsernamePreferenceTitle = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int SettingsItemTitle = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int UpdatingVpnTitle = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int VpnClientFormat = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int VpnItemPreferenceCategoryTitle = 2131165200;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int VeekeeTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
